language: bash
dist: trusty
install:
  - source cfg4dev
  - docker pull koalaman/shellcheck:latest
script:
  - pycodestyle
  - flake8
  - docker run -v "$PWD:/mnt" koalaman/shellcheck:latest $(find . -name \*.sh)
  - nosetests --with-coverage --cover-branches --cover-erase --cover-package dev_env
  - python bdist_wheel setup.py sdist --formats=gztar
