VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # per https://app.vagrantup.com/ubuntu/boxes/xenial64
  config.vm.box = "ubuntu/xenial64"
  # per this bug https://bugs.launchpad.net/cloud-images/+bug/1569237
  # pinning to a box version that fixes the bug
  # see https://app.vagrantup.com/ubuntu/boxes/xenial64/versions/20180420.0.0
  config.vm.box_version = "20180420.0.0"
  config.vm.provision "base", type: "shell", path: "https://raw.githubusercontent.com/simonsdave/dev-env/release-0.5.12/ubuntu/xenial/provision.sh", args: [
    "--timezone",
    ENV.fetch("VAGRANT_TIMEZONE", "EST"),
    ENV.fetch("VAGRANT_GITHUB_USERNAME", ""),
    ENV.fetch("VAGRANT_GITHUB_EMAIL", ""),
    ENV.fetch("VAGRANT_BASE64_ENCODED_GITHUB_SSH_PUBLIC_KEY", ""),
    ENV.fetch("VAGRANT_BASE64_ENCODED_GITHUB_SSH_PRIVATE_KEY", "")
  ]
  config.vm.provision "project", type: "shell", path: "provision.sh"
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", ENV.fetch("VAGRANT_MEMORY_IN_MB", "2048")]
  end
end
