VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "trusty"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  # :TODO: should probably make it possible to configure both the
  # guest and host port below
  # :WARNING: don't change the format of the line below
  # without also adjusting the code that's in provision.sh
  # which parses this line to configure nginx
  config.vm.network "forwarded_port", guest: 8085, host: 8085
  # :TODO: how do we deal with hardcoded branch name in URL below?
  config.vm.provision "base", type: "shell", path: "https://raw.githubusercontent.com/simonsdave/dev-env/master/ubuntu/trusty/provision.sh", args: [
    ENV.fetch("VAGRANT_GITHUB_USERNAME", ""),
    ENV.fetch("VAGRANT_GITHUB_EMAIL", ""),
    ENV.fetch("VAGRANT_BASE64_ENCODED_GITHUB_SSH_PUBLIC_KEY", ""),
    ENV.fetch("VAGRANT_BASE64_ENCODED_GITHUB_SSH_PRIVATE_KEY", "")
  ]
  config.vm.provision "project", type: "shell", path: "provision.sh"
  config.vm.provider :virtualbox do |vb|
    # :TODO: should be able to customize VM's memory
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
end
